### ISSUE TITLE
Narx qiymatlari $ (raqamlar) orasida letter specing qolib ketgan

### ISSUE THREAD

**Issue by Sardorbek-Raximberdiyev** [MIRZOULUGBEK9008/pricing-component-selfmade#1]
![image](https://user-images.githubusercontent.com/99403792/165871474-4b5fd283-465a-4ef2-8a9f-008c12592650.png)
![image](https://user-images.githubusercontent.com/99403792/165871547-3405651a-3f73-4f29-831d-a20b6cba1710.png)
-2px bo'lishi kerak edi

**Comment by MIRZOULUGBEK9008** [comment]
#fix
