### ISSUE TITLE
birinchi bolimda (Basic) padding 31px bo'lishi kerak edi 

### ISSUE THREAD

**Issue by Sardorbek-Raximberdiyev** [MIRZOULUGBEK9008/pricing-component-selfmade#3]
![image](https://user-images.githubusercontent.com/99403792/165871908-9979ddcf-ae27-4715-a344-cdd92d48db01.png)
bunday kichik maketlarda kichik piksellarga etibor berish kerak, menimcha

**Comment by MIRZOULUGBEK9008** [comment]
#fix
